#!/usr/bin/env python3
"""
即梦AI图片生成 - 火山引擎官方API
使用即梦同款V2.1文生图API
"""

import requests
import json
import sys
import os
from datetime import datetime, timezone
import hashlib
import hmac

def get_credentials():
    """获取API凭证"""
    try:
        with open('/root/.openclaw/.volc_access_key', 'r') as f:
            access_key = f.read().strip()
        with open('/root/.openclaw/.volc_secret_key', 'r') as f:
            secret_key = f.read().strip()
        return access_key, secret_key
    except Exception as e:
        print(f"❌ 无法读取API凭证: {e}")
        return None, None


def generate_image(prompt, width=1024, height=1024, style="电商"):
    """
    调用即梦AI生成图片
    
    Args:
        prompt: 提示词
        width: 图片宽度
        height: 图片高度
        style: 风格（电商/写实/插画等）
    """
    
    access_key, secret_key = get_credentials()
    if not access_key or not secret_key:
        return {"success": False, "error": "API凭证未配置"}
    
    # API配置
    service = "cv"
    region = "cn-north-1"
    host = "visual.volcengineapi.com"
    
    # 构建请求
    url = f"https://{host}/"
    
    # 请求体
    payload = {
        "req_key": "jimeng_high_aes_general_v21_L",
        "prompt": prompt,
        "width": width,
        "height": height,
        "seed": -1,
        "logo_text_content": "Generated by AI"
    }
    
    headers = {
        "Content-Type": "application/json",
        "X-Date": datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ"),
        "Authorization": f"HMAC-SHA256 Credential={access_key}/{datetime.now(timezone.utc).strftime('%Y%m%d')}/{region}/{service}/request"
    }
    
    try:
        response = requests.post(url, headers=headers, json=payload, timeout=60)
        if response.status_code == 200:
            data = response.json()
            if data.get("code") == 10000:
                return {
                    "success": True,
                    "image_url": data.get("data", {}).get("image_urls", [None])[0],
                    "prompt": prompt,
                    "request_id": data.get("request_id")
                }
            else:
                return {
                    "success": False,
                    "error": f"API错误: {data.get('message', '未知错误')}",
                    "code": data.get("code")
                }
        else:
            return {
                "success": False,
                "error": f"HTTP错误: {response.status_code}",
                "detail": response.text
            }
    except Exception as e:
        return {
            "success": False,
            "error": str(e)
        }


def generate_product_image(product, background="白色", style="简约"):
    """生成电商产品图"""
    
    # 构建专业电商提示词
    prompt_templates = {
        "简约": f"{background}背景，{product}，极简设计，专业产品摄影，45度角展示，柔和自然光，细腻阴影，8K超高清，电商主图风格，纯净背景，产品居中构图",
        "高端": f"{background}背景，{product}，奢华质感，金属光泽，高端产品摄影，精致细节，8K超高清，电商主图风格",
        "科技感": f"{background}背景，{product}，未来科技风格，发光元素，科技蓝，数字感，8K超高清，电商主图风格"
    }
    
    prompt = prompt_templates.get(style, prompt_templates["简约"])
    
    return generate_image(prompt, width=1024, height=1024)


def main():
    print("🎨 即梦AI图片生成（火山引擎官方API）")
    print("=" * 50)
    
    if len(sys.argv) > 1:
        product = ' '.join(sys.argv[1:])
    else:
        product = input("请输入产品名称: ")
    
    print(f"\n📦 正在生成: {product}")
    print("⏳ 请稍候...\n")
    
    result = generate_product_image(product)
    
    if result["success"]:
        print("✅ 图片生成成功!")
        print(f"📷 图片URL: {result.get('image_url', 'N/A')}")
        print(f"📝 提示词: {result['prompt']}")
        print(f"🔍 请求ID: {result.get('request_id', 'N/A')}")
    else:
        print(f"❌ 生成失败: {result.get('error', '未知错误')}")
        if result.get('code'):
            print(f"📋 错误码: {result['code']}")


if __name__ == "__main__":
    main()
